behaviors:
  AgentsController: # Harus sama dengan Behavior Name di Unity
    trainer_type: ppo # Algoritma training (PPO adalah pilihan umum yang baik)
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005  # Entropi, membantu eksplorasi
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear # atau constant
    network_settings:
      normalize: false
      hidden_units: 128 # Jumlah neuron di hidden layer
      num_layers: 2   # Jumlah hidden layer
      vis_encode_type: simple # Jika tidak menggunakan observasi visual
    reward_signals:
      extrinsic:
        gamma: 0.99 # Discount factor
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000 # Jumlah langkah total training (sesuaikan)
    time_horizon: 64
    summary_freq: 10000 # Seberapa sering menyimpan ringkasan untuk TensorBoard